# Force Node.js 20 and npm with specific configuration
[variables]
NODE_VERSION = "20"
NPM_CONFIG_ENGINE_STRICT = "false"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci --prefer-offline --no-audit --no-fund --maxsockets 1"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"