# Ultra-minimal configuration for memory-constrained deployment
[variables]
NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=512"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_ENGINE_STRICT = "false"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci --no-audit --no-fund --prefer-offline --maxsockets 1 --no-optional"

[phases.build]
cmd = "NODE_OPTIONS='--max-old-space-size=1024' npm run build"

[start]
cmd = "npm start"